### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by carlosedubarreto** [zhengyuf/IMavatar#25]
When I try to run the evaluation and it throws me this error.

Script
`python scripts/exp_runner.py --conf ./confs/IMavatar_unsupervised.conf --is_eval`

Error
```
(neural) D:\MOCAP\IMavatar\IMavatar\code>python scripts/exp_runner.py --conf ./confs/IMavatar_unsupervised.conf --is_eval
shell command : scripts/exp_runner.py --conf ./confs/IMavatar_unsupervised.conf --is_eval
Loading data ...
Finish loading data ...
creating the FLAME Decoder
Saving image 1 into ../data/experiments\yufeng\IMavatar_unsupervised\MVI_1810+MVI_1814\eval\MVI_1812\epoch_72
Traceback (most recent call last):
  File "D:\MOCAP\IMavatar\IMavatar\code\scripts\exp_runner.py", line 45, in <module>
    runner.run()
  File "D:\MOCAP\IMavatar\IMavatar\code\../code\scripts\test.py", line 129, in run
    plt.plot(img_name,
  File "D:\MOCAP\IMavatar\IMavatar\code\../code\utils\plots.py", line 44, in plot
    meshexport = mesh_util.generate_mesh(sdf_function, level_set=0, res_init=res_init, res_up=res_up)
  File "D:\MOCAP\IMavatar\IMavatar\code\../code\utils\mesh_util.py", line 22, in generate_mesh
    points = mesh_extractor.query()
  File "utils\libmise\mise.pyx", line 122, in utils.libmise.mise.MISE.query
    cdef long[:, :] points_view = points_np
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

```

Do you know how to solve this?

**Comment by carlosedubarreto** [comment]
I recompiled mise using int32 instead of int64 and it worked
![image](https://user-images.githubusercontent.com/4061130/191722201-0d665575-7d34-41f2-953a-f1d82f8930fd.png)
