### ISSUE TITLE
can you create a colab to test this?

### ISSUE THREAD

**Issue by loboere** [zhengyuf/IMavatar#34]
can you create a colab to test this?

**Comment by mhussar** [comment]
If anyone is checking this thread: I created a colab and got as far as being able to execute the exp_runner.py script but it failed. See below the exception message. I'm thinking maybe it has to do with the python version running on the colab? 
Anyone have any suggestions.
 
pyparsing.exceptions.ParseException: Expected '}', found '='  (at char 1869), (line:73, col:15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/exp_runner.py", line 31, in <module>
    runner = TrainRunner(conf=opt.conf,
  File "/content/IMavatar/code/../code/scripts/train.py", line 26, in __init__
    self.conf = ConfigFactory.parse_file(kwargs['conf'])
  File "/usr/local/lib/python3.8/site-packages/pyhocon/config_parser.py", line 142, in parse_file
    return cls.parse_string(content, os.path.dirname(filename), resolve, unresolved_value)
  File "/usr/local/lib/python3.8/site-packages/pyhocon/config_parser.py", line 192, in parse_string
    return ConfigParser().parse(content, basedir, resolve, unresolved_value)
  File "/usr/local/lib/python3.8/site-packages/pyhocon/config_parser.py", line 455, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/usr/local/lib/python3.8/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseSyntaxException: Expected '}', found '='  (at char 1869), (line:73, col:15)

**Comment by phoenix8875** [comment]
@mhussar @zhengyuf  same problem have you find any solution yet?
